apiVersion: batch/v1
kind: Job
metadata:
  name: db-migration
  namespace: ticket-app

spec:
  template:
    metadata:
      labels:
        app: db-migration
    spec:
      restartPolicy: OnFailure

      initContainers:
        - name: wait-for-db
          image: busybox:1.38
          command:
            - sh
            - -c
            - |
              until nc -z $DB_HOST $DB_PORT; do
                echo "Waiting for postgres..."
                sleep 2
              done
          env:
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  key: DB_HOST
                  name: api-config
            - name: DB_PORT
              valueFrom:
                configMapKeyRef:
                  key: DB_PORT
                  name: api-config

      containers:
        - name: db-migration
          image: kzak19/kubernetes-api
          imagePullPolicy: Always

          command:
            - sh
            - -c
            - |
              node ./src/migrate.js
          env:
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  key: DB_HOST
                  name: api-config
            - name: DB_PORT
              valueFrom:
                configMapKeyRef:
                  key: DB_PORT
                  name: api-config
            - name: DB_NAME
              valueFrom:
                configMapKeyRef:
                  key: POSTGRES_DB
                  name: postgres-config
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  key: POSTGRES_USER
                  name: postgres-secret
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: POSTGRES_PASSWORD
                  name: postgres-secret
