apiVersion: v1
kind: Service
metadata:
  namespace: ticket-app
  name: redis
  labels:
    group: redis
spec:
  type: ClusterIP
  selector:
    app: redis
  ports:
    - port: 6379
      targetPort: 6379
