apiVersion: v1
kind: Service
metadata:
  namespace: ticket-app
  name: postgres
  labels:
    group: db
spec:
  clusterIP: None

  selector:
    app: postgres
  ports:
    - port: 5432
      targetPort: 5432
