apiVersion: v1
kind: Service
metadata:
  namespace: ticket-app
  name: worker
  labels:
    group: worker
spec:
  type: ClusterIP
  selector:
    app: worker
  ports:
    - port: 8081
      targetPort: 8081
